FROM python:3.12.7-slim-bullseye AS builder

ENV PYTHONUNBUFFERED 1

RUN mkdir /install
WORKDIR /install

COPY requirements.txt /requirements.txt

RUN pip install --prefix=/install -r /requirements.txt

# STAGE 2
FROM python:3.12.7-slim-bullseye

ENV PYTHONUNBUFFERED 1

COPY --from=builder /install /usr/local
COPY calculate_trips.py /app/calculate_trips.py
COPY pull_stations.py /app/pull_stations.py
COPY run_scripts.sh /app/run_scripts.sh

WORKDIR /app

RUN chmod +x /app/run_scripts.sh

ENTRYPOINT ["/app/run_scripts.sh"]
