FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
COPY nextbike_processing/ ./nextbike_processing/
COPY entrypoint.sh .

RUN pip install --no-cache-dir -r requirements.txt && \
    chmod +x entrypoint.sh

ENV PYTHONPATH="/app"

ENTRYPOINT ["./entrypoint.sh"]
