FROM python:3.11

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY data_collection/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY data_collection /app

CMD ["python", "query_nextbike.py"]
