FROM python:3.11-alpine AS builder

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY data_collection/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --prefix=/install -r /app/requirements.txt

# STAGE 2
FROM python:3.11-alpine

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY --from=builder /install /usr/local
COPY data_collection /app

CMD ["python", "query_nextbike.py"]


